# Generated by Django 5.2.14 on 2026-05-26 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('dimension', models.CharField(blank=True, max_length=64)),
                ('is_canonical', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='SourceMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=20)),
                ('source_field', models.CharField(max_length=120)),
                ('normalized_field', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['source_type', 'source_field'],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_field'), name='unique_source_mapping')],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=120)),
                ('factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('scope', models.CharField(blank=True, max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_factors', to='reference_data.unit')),
            ],
            options={
                'ordering': ['activity_type', 'unit__symbol'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiplier', models.DecimalField(decimal_places=8, max_digits=18)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='reference_data.unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='reference_data.unit')),
            ],
            options={
                'ordering': ['from_unit__symbol', 'to_unit__symbol'],
                'constraints': [models.UniqueConstraint(fields=('from_unit', 'to_unit'), name='unique_unit_conversion')],
            },
        ),
    ]
