# Generated by Django 5.2.14 on 2026-05-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_tenant__1b33be_idx',
            old_name='audit_tenant_object_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_tenant__d8cd3e_idx',
            old_name='audit_tenant_actor_idx',
        ),
    ]
