# Generated by Django 5.2.14 on 2026-05-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='ingestions/%Y/%m/%d'),
        ),
    ]
