# Generated by Django 5.2.14 on 2026-05-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normalizedrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='normalizedrecord',
            new_name='normalizati_tenant__91d465_idx',
            old_name='normalizati_tenant__8ec78c_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedrecord',
            new_name='normalizati_tenant__c73b22_idx',
            old_name='normalizati_tenant__a99634_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedrecord',
            new_name='normalizati_tenant__3b9573_idx',
            old_name='normalizati_tenant__d86e2f_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedrecord',
            new_name='normalizati_tenant__25de2d_idx',
            old_name='normalizati_tenant__7bcc5c_idx',
        ),
    ]
